version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: semanticallynull/container-chaos
    steps:
      - run: uname -a
      - run: hostname -f
